### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by awptechnologies** [marmotteio/marmotteio#3]
This is not working i get a server error when logging in with default credentials

**Comment by zenati** [comment]
Hi @awptechnologies, can you detail the issue you're having. Did you use Docker? Docker-compose? Can you print out the error our log? We'll make sure you get it up and running.

**Comment by awptechnologies** [comment]
I used docker compose. When the container loads the images are messed up on home page. When I log in I get error 500. I'll mess with it tonight and screen shot what I have going on.

**Comment by zenati** [comment]
@awptechnologies I added ASSET_URL to the docker-compose.yml that might be the issue you're having.
Can you, git pull, delete any marmotteio docker image you have, and then docker-compose up.

Also, if you're using Google Chrome and running locally, you might need to :

Go to chrome://net-internals/#hsts
and under "Delete domain security policies", input and delete "localhost".

If you still have the issue, can you screenshot it please.
