### ISSUE TITLE
PHP Warning:  require(/app/vendor/autoload.php)

### ISSUE THREAD

**Issue by NightHawkATL** [marmotteio/marmotteio#4]
I get an error when trying to deploy with portainer (docker compose stack).

PHP Warning:  require(/app/vendor/autoload.php): Failed to open stream: No such file or directory in /app/artisan on line 18
PHP Warning:  require(/app/vendor/autoload.php): Failed to open stream: No such file or directory in /app/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /app/artisan:18
Stack trace:
#0 {main}
  thrown in /app/artisan on line 18

I did clone the git repo so I have all the files needed but I am still getting this error. I do not se a "vendor" folder from the repo clone.

![image](https://github.com/marmotteio/marmotteio/assets/8395658/46383ede-eeba-4e55-a666-55449772f7b0)

**Comment by zenati** [comment]
hello @NightHawkATL since you cloned from the repo you have two choices, either use docker compose, or use marmotte in local. To use it in local you have to:
- composer install
- npm install && npm run build
- php artisan key:generate
- rename .env.example to .env
- update the .env to point to your local DB (make sure it's created)
- php artisan migrate --seed
- finally: php artisan serve

**Comment by zenati** [comment]
You also have the option to create an account and use it right away from https://marmotte.io/

**Comment by NightHawkATL** [comment]
![image](https://github.com/marmotteio/marmotteio/assets/8395658/0e695deb-b289-4bf9-a9f3-f45f4bd23575)

I would like to try it out self-hosted as that will mean that all my data stays local.

**Comment by zenati** [comment]
@NightHawkATL OK. The project already has a docker-compose.yml file already filled in with the server + mariadb.
And the image you're using looks good to me, and already has the vendor folder.

You can also run marmotte using Docker directly, see Readme:

https://github.com/marmotteio/marmotteio/?tab=readme-ov-file#running-marmotte-with-docker

**Comment by NightHawkATL** [comment]
![image](https://github.com/marmotteio/marmotteio/assets/8395658/c24f166e-65f7-4661-837f-322c7dff7197)

This is using docker directly since you think that it is the only way to deploy. Same error..

**Comment by NightHawkATL** [comment]
tried with the default docker compose with mysql and get an error after logging in with the default credentials saying that the sql DB is messed up or something is missing.

I saw the ad from watching a DBTech video and thought I would give it a try. I have been messing with it for an hour and it is time to give up. Please let us know when this is fixed and will work better self-hosted as I do not want to pay for a cloud-hosted version since I would like to have access even when offline.

**Comment by NightHawkATL** [comment]
closing issue

**Comment by zenati** [comment]
@NightHawkATL are you running inside a VM? Proxmox? CE?

**Comment by NightHawkATL** [comment]
I am running a docker vm on Proxmox. Proxmox is up to date since yesterday. Portainer is BE and is 2.19.4. VM was updated yesterday as well.
